package.json
src/flavors/react/components/form/RadioField/index.tsx

* fixed bug when two radio fields are displayed (ids are beig repeated)

Fixed option id

---

package.json
src/flavors/react/components/form/RadioField/index.tsx

fixed radio custom columns

---

package.json
src/core/components/ProgressBar.styl
src/flavors/react/components/ProgressBar/ProgressBar.stories.tsx
src/flavors/react/components/ProgressBar/index.tsx
src/flavors/react/index.ts

added progress bar component to design system

---

package.json
src/flavors/pug/components/form/SelectField/Demos/Container.pug
src/flavors/pug/components/form/SelectField/Demos/Default.pug
src/flavors/pug/components/form/SelectField/SelectField.stories.js
src/flavors/pug/components/form/SelectField/index.pug

- Add select field on blueberry pug version

feat: Add select field pug

---

package.json
src/flavors/pug/components/form/SelectField/SelectField.stories.js
src/flavors/pug/components/form/SelectField/index.pug
src/flavors/pug/components/form/SelectField/script.js

- Change option color when value is not empty

fix: add script to change placeholder color

---

package.json
src/flavors/react/components/form/Checkbox/Checkbox.stories.tsx
src/flavors/react/components/form/Checkbox/index.tsx
src/flavors/react/components/form/InputField/Input.stories.tsx
src/flavors/react/components/form/SearchField/SearchField.stories.tsx

fix: 🐛 fixed checkbox doc

---

package.json
src/core/components/Form.styl
src/flavors/react/components/form/TextareaField/TextareaField.stories.tsx
src/flavors/react/components/form/TextareaField/index.tsx
src/flavors/react/index.ts

feat: added textarea component

---

package.json
src/flavors/react/components/form/AutocompleteField/index.tsx
src/flavors/react/components/form/RadioField/index.tsx
src/flavors/react/helpers/utils.ts
yarn.lock

* `RandomString` lib was breaking ESBuild

fix: 🐛 removed broken lib

---

package.json
src/core/data/footer-links.json

* Removed the Iq contas list item from the footer component;

chore: 🔥 removed the iq contas link from footer

---

package.json
src/flavors/pug/components/legacy/FooterClassic/index.pug

* Removing iq contas footer item from the **pug** footer component

fix: 🐛 removed iqc footer item from pug footer

---

package.json
src/core/components/Accordion.styl
src/flavors/react/components/Accordion/Item/index.tsx
src/flavors/react/components/Toast/index.tsx
src/flavors/react/components/form/AutocompleteField/index.tsx
src/flavors/react/components/legacy/FooterClassic/index.tsx
src/flavors/react/components/legacy/HeaderClassic/data.ts
src/flavors/react/components/legacy/HeaderClassic/index.tsx
src/flavors/react/components/legacy/HeaderClassic/subcomponents/HamburgerButton.tsx
src/flavors/react/components/legacy/HeaderClassic/subcomponents/IqLogo.tsx
src/flavors/react/components/legacy/HeaderClassic/subcomponents/LoggedOutNavigation.tsx
src/flavors/react/components/legacy/HeaderClassic/types.tsx

This PR fix the accessibility issues

Fix/iql 9370/accessibility

---

package.json
src/flavors/react/components/form/InputField/index.tsx

this PR removes mask dependency for input texts

[IQ-TECH] - Remove mask text dependency

---

package.json
src/flavors/react/components/form/SelectField/SelectField.stories.tsx
src/flavors/react/components/form/SelectField/index.tsx
yarn.lock

this PR improves the accessibility.
- Added `aria-label` in `SelectField` component.

fix: accessibility improvements

---

package.json
src/flavors/react/components/CentralizedModal/index.tsx
src/flavors/react/components/ConfirmationModal/index.tsx

fix: accessibility improvements 

---

package.json
src/flavors/pug/components/legacy/HeaderClassic/subcomponents/Navigation.pug
src/flavors/react/components/Header/data.ts
src/flavors/react/components/legacy/HeaderClassic/data.ts

refactor: :fire: removing header item

---

package.json
src/flavors/react/components/Tooltip/index.tsx

adding 'custonButton' prop to tooltip component.

feat: :sparkles: adding custonButton prop to tooltip

---

package.json
src/flavors/react/components/form/AutocompleteField/hook.ts
yarn.lock

* removed focus rule to change autofill field

Removed possibly unused rule

---

package.json
src/core/data/public-info.json
src/flavors/pug/components/legacy/FooterClassic/subcomponents/FooterInfo.pug

changing the text where it mentions the address of the company IQ

refactor: :recycle: changing IQ address

---

rollup.config.js
tasks/process-files/icons/react-icons/generate-dist-icons.js

This PR:
Add missing dependencies to fix build.

fix: build depency injection

---

package.json
src/core/components/legacy/HeaderClassic.styl
src/flavors/react/components/legacy/HeaderClassic/hook.ts
src/flavors/react/components/legacy/HeaderClassic/index.tsx
src/flavors/react/components/legacy/HeaderClassic/subcomponents/IqLogo.tsx
src/flavors/react/components/legacy/HeaderClassic/subcomponents/LoggedInNavigation.tsx
src/flavors/react/components/legacy/HeaderClassic/types.tsx

Adds the customLoggedInMenuItems option to the LegacyHeader component.
This will allow us to create dynamic menus

Dynamic Menu

---

package.json
src/core/components/legacy/HeaderClassic.styl
src/flavors/react/components/legacy/HeaderClassic/HeaderClassic.stories.tsx
src/flavors/react/components/legacy/HeaderClassic/index.tsx
src/flavors/react/components/legacy/HeaderClassic/subcomponents/IqLogo.tsx
src/flavors/react/components/legacy/HeaderClassic/subcomponents/LoggedInNavigation.tsx
src/flavors/react/components/legacy/HeaderClassic/types.tsx

This PR adds new onClick events on legacy navbar (IQ logo and Profile button)

custom onClick functions

---

package.json
src/core/components/legacy/HeaderClassic.styl

Remove overflowX when mobile menu is open

FIX: Legacy header - mobile

---

package.json
src/core/components/Header.styl
src/core/components/legacy/HeaderClassic.styl
src/flavors/react/components/Header/data.ts
src/flavors/react/components/Header/subcomponents/AuthButttons.tsx
src/flavors/react/components/legacy/HeaderClassic/HeaderClassic.stories.tsx
src/flavors/react/components/legacy/HeaderClassic/data.ts
src/flavors/react/components/legacy/HeaderClassic/hook.ts
src/flavors/react/components/legacy/HeaderClassic/index.tsx
src/flavors/react/components/legacy/HeaderClassic/subcomponents/AuthButtons.tsx
src/flavors/react/components/legacy/HeaderClassic/subcomponents/LoggedInNavigation.tsx
src/flavors/react/components/legacy/HeaderClassic/subcomponents/LoggedOutNavigation.tsx
src/flavors/react/components/legacy/HeaderClassic/types.tsx

- Refactor: Change legacy header to work without variant
- Feat: Add new score item on Header and new Auth buttons

New Header

---

package.json
src/flavors/react/components/form/TokenField/hook.ts
src/flavors/react/components/form/TokenField/index.tsx

This PR:
- Fix token field types (function args)
- Add missing props (invalid and disabled)

Fix: tokenField

---

package.json
src/flavors/react/components/Header/subcomponents/AuthButttons.tsx

This PR takes the parameters from the URL and adds it to the redirectToPath function link.

Feat: adding parameters in header auth buttons

---

package.json
src/flavors/react/components/legacy/HeaderClassic/subcomponents/AuthButtons.tsx

This PR takes the parameters from the URL and adds it to the redirectToPath function link (header legacy).

Feat: adding parameters in header legacy auth buttons

---

package.json
src/flavors/react/components/form/PasswordField/index.tsx

This PRs adds inputRef prop on PasswordField component

Feat: Ref on PaswwordField

---

package.json
src/flavors/react/components/Accordion/Accodion.stories.tsx
src/flavors/react/components/Accordion/Item/index.tsx
src/flavors/react/components/Accordion/Item/logic.ts
src/flavors/react/components/Accordion/types.ts

- add a function callback on accorsion component

chore: version up

---

package.json
src/core/components/Form.styl
src/flavors/react/components/form/TokenField/Token.stories.tsx
src/flavors/react/components/form/TokenField/index.tsx

Types: 
- Number - Default
- Password
- Text

add type on TokenField input

---

package.json
src/core/data/public-info.json
src/flavors/pug/components/legacy/FooterClassic/subcomponents/FooterInfo.pug

This PR changes the company name at footer components

[GTW-639] Change company at footer

---

package.json
src/core/components/HeaderCP.styl
src/flavors/react/components/FooterCP/index.tsx
src/flavors/react/components/FooterCP/subcomponents/LinksGroup.tsx
src/flavors/react/components/FooterCP/subcomponents/SocialIcons.tsx
yarn.lock

This PR fix some layout problems on HeaderCP and FooterCP components after using them on a project.

[GTW-713] HeaderCP and Footer CP adjustments

---

package.json
src/core/components/FooterCP.styl
src/flavors/react/components/FooterCP/index.tsx
src/flavors/react/components/FooterCP/subcomponents/AppStores.tsx

Links para baixar o app nas lojas adicionados no rodapé.

[GTW-1008] Link para as lojas do app no rodapé
